### ISSUE TITLE
Create a new release to allow telemetry 1.0 or even 1.1

### ISSUE THREAD

**Issue by hdahlheim** [elixir-toniq/regulator#12]
Hey, is it possible to tag a new release and push it to hex.pm that includes [the change to allow the usage of telemetry 1.0](https://github.com/elixir-toniq/regulator/commit/d257e15c3a605ef4442b72aa8360ef1ec3e5df4e)? 
Or maybe even change the mix.exs to allow telemetry 1.1? Currently, telemetry gets downgraded to 1.0 when including regulator.

Pulling it in over git works fine, but a release on hex that works with new phoenix apps would be nice :)

**Comment by keathley** [comment]
Sure @hdahlheim. I'll do this once I'm sitting at a real computer.

**Comment by keathley** [comment]
Done.
